session_name: dev
before_script: clear
windows:
  - window_name: dev
    layout: main-horizontal
    focus: true
    panes:
      - shell: /usr/bin/env nvim .
      - focus: true
        shell_command: ""
