language: bash

jobs:
  include:
    - os: linux
      dist: trusty
    - os: osx

before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install shellcheck; fi

script:
  - shellcheck -x $(find . -name "*.sh") bash/bash_profile bash/bashrc
