# Inserts a blank line between shell prompts
add_newline = true

format = """(${status}${cmd_duration}\n)\
${username}@${hostname}: ${directory}\
${git_branch}${git_state}${git_metrics}${git_status}\
${docker_context}\
${package}\
${golang}\
${python}\
${rust}\
${terraform}\
${vagrant}\
${kubernetes}\
${line_break}\
${shlvl}\
${jobs}\
${battery}\
${character}
"""


[status]
disabled = false
format = "(code: [${symbol} ${status}](${style})  )"

[cmd_duration]
format = "(duration: [${duration}]($style))"

[character]
success_symbol = "[>](bold)"
# Set the error symbol to be plain, like the success symbol. Error is shown by the 'status' module instead
error_symbol = "[>](bold)"
#error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[username]
style_user = "bold green"
style_root = "bold red"
show_always = true
format = "[$user](${style})"

[hostname]
style = "bold green"
ssh_only = false
trim_at = ""
format = "[${hostname}](${style})"

[directory]
style = "bold blue"
read_only = ""
truncation_length = 5
truncate_to_repo = false

[docker_context]
symbol = " "

[git_branch]
style = "bold yellow"
# Add '(' to the beginning. The closing ')' is at the end of the 'git_status' section
format = "[\\(${branch}](${style})"

[git_state]
style = "bold yellow"

[git_metrics]
added_style = "yellow"
deleted_style = "dimmed yellow"

[git_status]
style = "bold yellow"
# Add a ') ' to the end. The opening '(' is at the start of the 'git_branch' section
format = '([\[${all_status}${ahead_behind}\]\) ](${style}))'

[shlvl]
disabled = false
symbol = " "
style = "bold cyan"
format = "[(${symbol}${shlvl} )](${style})"

[jobs]
style = "purple"

[golang]
symbol = " "

[memory_usage]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
