#!/usr/bin/env bash

# Lint files according to their file extensions
linter="${HOME}/repo/scripts/lint.sh"
if [[ -f "${linter}" ]]; then

    # Grab files added to commit
    changedFiles=$(git diff --cached --name-only --diff-filter=ACMR)

    echo '-------------------------'
    echo 'PRE-COMMIT HOOK'
    # Run the linter
    "${linter}" "${changedFiles}"
    echo '-------------------------'

else
    echo "Heads up, your pre-commit lit script doesn't exist"
fi
