# /etc/zsh/zlogin: user .zlogin file for zsh(1).
#
# This file is sourced only for login shells. It
# should contain commands that should be executed only
# in login shells. It should be used to set the terminal
# type and run a series of external commands (fortune,
# msgs, from, etc.)
#
# Starup Order: zshenv, zprofile, zshrc, zlogin

# If running from tty1 start sway
[ "$(tty)" = "/dev/tty1" ] && exec sway --my-next-gpu-wont-be-nvidia

fortune #| cowsay # commented out because cowsay takes up too much space in a tmux popup window :(
