# /etc/zsh/zprofile: user .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Startup Order: zshenv, zprofile, zshrc, zlogin
