# /etc/zsh/zshenv: user .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Startup Order: zshenv, zprofile, zshrc, zlogin

# --------------------------------------------------
# Directory setup
# --------------------------------------------------
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"


# --------------------------------------------------
# History
# --------------------------------------------------
export HISTFILE="${XDG_CACHE_HOME}/zsh/history"
export HISTSIZE=100000
export SAVEHIST=100000


# --------------------------------------------------
# Colors
# --------------------------------------------------
# Heads up: Colors are mapped to the Pywal Monokai scheme
# TODO: checkout color heading from https://github.com/dylanaraps/pure-sh-bible#get-the-directory-name-of-a-file-path
export RED='\033[31m'
export GREEN='\033[32m'
export YELLOW='\033[33m'
export BLUE='\033[34m'
export BLACK='\033[90m'
export PURPLE='\033[35m'
export CYAN='\033[35m'
export NO_COLOR='\033[m'
export UNDERLINE_ON='\033[4m'
export UNDERLINE_OFF='\033[24m'
export BOLD_ON='\033[1m'
export BOLD_OFF='\033[21m'

# Set less colors
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;34m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_us=$'\e[1;4;31m'
export LESS_TERMCAP_ue=$'\e[0m'
# Bash bug: exporting 'LESS_TERMCAP_us' last with 'set -x' makes all set -x output print red


# --------------------------------------------------
# Pager & Editor
# --------------------------------------------------
export EDITOR='vim'
# Set less as the default pager (like when reading man pages)
export PAGER="less"
# '-R' interprets terminal color escape codes, '-F' quits if content is less than 1 page (acts more like cat for short files), 'LONG-PROMPT' intentionally capitalized for an even longer prompt
export LESS='-RF --LONG-PROMPT --mouse --wheel-lines=5'


# --------------------------------------------------
# Force tools to conform to XDG base directory specification
# --------------------------------------------------
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/config"
export BAT_CONFIG_PATH="${XDG_CONFIG_HOME}/bat/bat.conf"
export PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/pythonrc.py"

# --------------------------------------------------
# Path
# --------------------------------------------------
export PATH="${HOME}/.cargo/bin:${PATH}"
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/repo/scripts:${PATH}"
export PATH="${HOME}/.pyenv/bin:${PATH}"

if [ -e /home/sarcos/.nix-profile/etc/profile.d/nix.sh ]; then . /home/sarcos/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
