#!/usr/bin/env bash

# Grab files added to commit
changedFiles=$(git diff --cached --name-only --diff-filter=ACMR)

# Lint files according to their file extensions
echo '-------------------------'
echo '> Global pre-commit linter'

echo "TODO"

echo '< End Global pre-commit linter'
echo '-------------------------'



############### Run local git hooks if they exist ###############
echo '> Local pre-commit script'
set -eu
hook_name="$(basename "$0")"
hook_script=".git/hooks/$hook_name"
if [[ -e "$hook_script" ]]; then
    eval "$hook_script"
fi
echo '< End local pre-commit script'
echo '-------------------------'
