#!/usr/bin/env bash

KEY_DIR="${HOME}/.ssh"
KEY="${KEY_DIR}/id_rsa"

mkdir -p "${KEY_DIR}"

if [[ ! -f "${KEY}" ]]; then
  echo "Generating ssh key"
  comment="$(whoami)@$(hostname) Generated $(date)"
  # -N "" for empty passphrase
  ssh-keygen -b 4096 -t rsa -f "${KEY}" -N "" -C "${comment}"
else
  echo "ssh key already exists"
fi

